### ISSUE TITLE
Google Chrome stable version 47 - SimpleWebRTC does not work anymore.

### ISSUE THREAD

**Issue by shamun** [andyet/SimpleWebRTC#360] opened 2015-12-01 23:47 UTC
Since Google Chrome Stable version 47 is now stable. All SimpleWebRTC applications are not working anymore, before in 46 it was all working fine.

Usage:

1 - root url: http://www.example.com/login
2 - after login it has iframe opening https://subdomain.example.com/simplewebrtc

We keep getting this shield icon or no shield icon at all and only that error "switching your application to a secure origin, such as HTTPS". It was always working before 47 version.

![Image of ERROR detials](http://i.stack.imgur.com/K3R5E.png)

How can it be fixed please? we have also tried 

```
Windows 8:

"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --allow-running-insecure-content

OSX 10.11:

'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --allow-running-insecure-content
```

But no luck, iframe keep failing to load SimpleWebRTC.

**Comment by shamun** [comment] 2015-12-02 00:53
Chrome issue created related to this: https://code.google.com/p/chromium/issues/detail?id=564330

**Comment by tgabi333** [comment] 2015-12-02 04:39
See: https://twitter.com/juberti/status/659192698214023168

**Comment by xdumaine** [comment] 2015-12-02 15:22
@shamun As @tgabi333 mentioned, `getUserMedia` no longer works on insecure (http) origins. You'll need to serve your site with tls (https). The Errors you're encountering are specific to chrome security requirements and cannot be resolved with SimpleWebRTC, so I'm closing this issue. Follow up on the Chrome ticket, or (more likely, since this is expected behavior), discuss in discuss-webrtc google group to learn how to work around this.

**Closed by xdumaine** 2015-12-02 15:22 UTC
