### ISSUE TITLE
TURN Server with Firefox-Chrome: "ICE failed, see about:webrtc for more details"

### ISSUE THREAD

**Issue by Hirtenknogger** [andyet/SimpleWebRTC#414] opened 2016-03-17 08:23 UTC
I use Coturn as TURN server with TURN REST API for authentication.
To test Coturn i forced SimpleWebRTC to use relay.
Everything works good between firefox-firefox and chrome-chrome.
But there is a problem between firefox-chrome.

Fireofx console says:
`ICE failed, see about:webrtc for more details`

about:webrtc says:
`Error parsing attribute: a=candidate:392817652 1 udp 41754367 192.168.178.59 54512 typ relay raddr 0.0.0.0 rport 0 generation 0 ufrag CHBOjbay7Itekf5k`

**Comment by fippo** [comment] 2016-03-17 09:01
what Firefox version are you using? Do you have a page to reproduce?
I'd be quite surprised if those candidates chrome generates (since 49 or 50?) would cause issues in Firefox

**Comment by Hirtenknogger** [comment] 2016-03-17 09:25
I use firefox 45.0 and Chrome 49.0. I have no page to reproduce.

I am setting:
`peerConnectionConfig:{
      iceTransports: 'relay'
 },`
in my Constructor.

Firefox candidate is:
`a=candidate:3 1 UDP 92217343 192.168.178.59 54474 typ relay raddr 192.168.178.59 rport 54474`

Chrome candidate is:
`a=candidate:392817652 1 udp 41754367 192.168.178.59 54512 typ relay raddr 0.0.0.0 rport 0 generation 0 ufrag CHBOjbay7Itekf5k`

I think the problem occurs because Chrome sets raddr 0.0.0.0 and rport 0.

**Comment by Hirtenknogger** [comment] 2016-03-17 09:29
When I do not set
`peerConnectionConfig:{ iceTransports: 'relay' }`

then Chrome generates:
`a=candidate:392817652 1 udp 41754367 192.168.178.59 49726 typ relay raddr 192.168.178.46 rport 51767 generation 0 ufrag x5TaH1FAjrprUsMD`

**Comment by fippo** [comment] 2016-03-17 09:38
ok... I can reproduce that by going to https://simplewebrtc.com/audio in chrome, setting
```
webrtc.webrtc.config.peerConnectionConfig.iceTransports = 'relay'
```
and then joining with a firefox that has the relay-only flag set.

Let me ping some people...

**Comment by Hirtenknogger** [comment] 2016-03-17 09:44
Thank you very much!

**Comment by fippo** [comment] 2016-03-17 10:06
filed https://bugzilla.mozilla.org/show_bug.cgi?id=1257472

**Comment by xdumaine** [comment] 2016-03-17 16:28
Closing here since the firefox bug has acknowledged and is resolving.

**Closed by xdumaine** 2016-03-17 16:28 UTC

**Comment by fippo** [comment] 2016-03-18 07:22
yes, many things to @mairereavy + team for fixing it with very high priority. It still baffles me that in the 12+ months since this landed in Chrome nobody has run into this issue :-(

@Hirtenknogger given how fast this will roll out I don't think it makes sense to add an official workaround in simplewebrtc, but if you need to solve it today try adding this before the peers.foreach [here](https://github.com/andyet/SimpleWebRTC/blob/f78bc2596c3b69a42f91dde229ff960055ae373a/simplewebrtc.js#L103-L104)
```
            if (message.type === 'candidate') {
                var cand = message.payload.candidate.candidate.split(' ');
                if (cand[7] === 'relay' && cand[10] === 'rport' && cand[11] === '0') {
                    cand[11] = '9';
                    message.payload.candidate.candidate = cand.join(' ');
                }
            }
```
and let me know if that doesn't fix it.

**Comment by Hirtenknogger** [comment] 2016-03-18 09:35
@fippo thank you for your help and creating a flied on bugzilla !

Yor workaround fixes the bug temporary! I am looking forward to a new firefox version.
THX!

**Comment by Byakuran** [comment] 2017-01-13 08:05
hi,my english is so terrible,I encountered the same problem.
can you tell me how to solve this problem or why did it happend?

**Comment by fippo** [comment] 2017-01-13 08:08
@Byakuran your issue is most likely unrelated to this (which has been fixed for a while). See [My WebRTC app works locally but not on a different network](http://testrtc.com/webrtc-api-trace/)
